spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:2333/avalon?serverTimezone=UTC
    username: root
    password: FTY19132

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8888